# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
#   - name: WhitespaceTokenizer
#   - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#   - name: CountVectorsFeaturizer
#     analyzer: char_wb
#     min_ngram: 1
#     max_ngram: 4
#   - name: DIETClassifier
#     epochs: 100
#     constrain_similarities: true
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100
#     constrain_similarities: true
#   - name: FallbackClassifier
#     threshold: 0.3
#     ambiguity_threshold: 0.1

    # 0. Language Model
    # Using SpacyNLP pre-trained language model to initialize spaCy structures and use pre-trained word vectors
    # (strings/utterances).
    - name: "SpacyNLP"
      model: "en_core_web_md" # English (en) pipeline optimized for CPU with medium size
      case_sensitive: false # Not case-sensitive i.e. "Hello" and "hello" are understood as the same
    # 1. Tokenizers
    # (Not) Using the Whitespace Tokenizer to separate words at whitespaces
    # - name: WhitespaceTokenizer
    # Using SpacyTokenizer to separate the utterances into tokens based on configuration
    - name: SpacyTokenizer
      intent_tokenization_flag: false # Setting it to false to avoid splitting intents
      intent_split_symbol: " " # Delimiter on which intents will be split
      token_pattern: None # NO regular expression to detect tokens
    # 2. Featurizers
    # Using the SpacyFeaturizer to create vector representation of user messages and responses based on spaCy
    # instruction-set
    - name: SpacyFeaturizer
    # Using the RegexFeaturizer to create vector representation of user messages (only) based on regular expressions
    - name: RegexFeaturizer
    # Using the LexicalSyntacticFeaturizer to create lexical and syntatic features for user messages (only) supporting
    # entity extraction
    - name: LexicalSyntacticFeaturizer
    # Using the CountVectorsFeaturizer to create groupings of words from user messages, intents and responses
    - name: CountVectorsFeaturizer
      # char_wb creats character n-grams (char) only from text inside the specified word boundaries (wb)
      analyzer: char_wb
      min_ngram: 1 # Minimum of a unigram
      max_ngram: 4 # Maximum of a quadrigram
    # 3. Intent Classifier & 4. Entity Extractors
    # Using DIETClassifier for both intent classification and entity extraction
    - name: DIETClassifier
      epochs: 100 # Train the classifier for 100 epochs i.e. 100 iterations over the training dataset
      constrain_similarities: true # Using sigmoid (logistic) function to scale down high similarities to low
      # Using softmax to normalize the computed dot products for confidence determination
      model_confidence: softmax
    # Using EntitySynonymMapper to associate synonymous entities (e.g. "Hi" with "Hello")
    - name: EntitySynonymMapper
    # 5. Selectors
    # Using ResponseSelector to generate a database of predicted responses with its confidence
    - name: ResponseSelector
      epochs: 100 # Train the selector for 100 epochs i.e. 100 iterations over the training dataset
      constrain_similarities: true # Using sigmoid (logistic) function to scale down high similarities to low
    # Using ResponseSelector to generate a database of predicted responses with its confidence
    - name: ResponseSelector
      epochs: 100 # Train the selector for 100 epochs i.e. 100 iterations over the training dataset
      retrieval_intent: chitchat # Handling the Rasa chitchat retrieval intent
      constrain_similarities: true # Using sigmoid (logistic) function to scale down high similarities to low
    # Using ResponseSelector to generate a database of predicted responses with its confidence
    - name: ResponseSelector
      epochs: 100 # Train the selector for 100 epochs i.e. 100 iterations over the training dataset
      retrieval_intent: faq # Handling the FAQs retrieval intent
      constrain_similarities: true # Using sigmoid (logistic) function to scale down high similarities to low
    # 6. FallbackClassifier for assigning boilerplate intents where the actual classification scores are ambiguous or
    # confidence lower than threshold)
    - name: FallbackClassifier
      # Setting a classification threshold value of 0.3 (any classification scores lower than this, have
      # "nlu_fallback" intent assigned)
      threshold: 0.3
      # Setting an ambiguity threshold value of 0.1 (any two different intents closer than this, have "nlu_fallback"
      # intent assigned)
      ambiguity_threshold: 0.1
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
   - name: MemoizationPolicy
   - name: RulePolicy
   - name: UnexpecTEDIntentPolicy
     max_history: 5
     epochs: 100
   - name: TEDPolicy
     max_history: 5
     epochs: 100
     constrain_similarities: true
